language: node_js

node_js:
  - 6.14.0
  - 9
  - 10

script:
- npm run lint
- npm run test:cov
- npm run build

sudo: false

deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  on:
    node: '10'

after_success:
- bash <(curl -s https://codecov.io/bash)
